### ISSUE TITLE
Hide the badge count of unread messages in muted chats

### ISSUE THREAD

**Issue by hatarist** [overtake/telegram#141]
Currently the desktop application shows the unread messages' badge count in Dock even if the chat (that has unread messages) is muted.

I'd love to have ability not to show the unread messages counter if the chat is muted - since it's muted, it's pretty distracting to see unread messages from the distracting/unwanted chats.

Personally, I don't mind the red badge on the "Chats" tab, but the Dock's badge is pretty distracting.

![screenshot](https://cloud.githubusercontent.com/assets/2741725/8279033/343b28c6-18d9-11e5-9409-517e7fe645ea.png)

**Comment by jacobrichard** [comment]
+1

**Comment by TyBrown** [comment]
+1

**Comment by MrGluek** [comment]
Please do Slack-like notifications - number for unmuted unread and dot  if unread messages are in muted chats.

**Comment by SolvvyInc** [comment]
+1

**Comment by zeeraw** [comment]
+1 – Since my Telegram client is always visible, muting doesn't really do anything for me if the badge shows up every time there's a new message.

**Comment by entropious** [comment]
+1

**Comment by overtake** [comment]
OK, guys. I added this feature to beta. Can try it now - https://rink.hockeyapp.net/apps/c55f5e74ae5d0ad254df29f71a1b5f0e/app_versions/660

**Comment by jacobrichard** [comment]
Verified that this works. You need to go to Settings -> General and set your preference for 'Include muted chats in unread badge'

**Comment by gsamat** [comment]
Sorry for offtopic.

Where should I go to upvote same issue for the official iOS client?

**Comment by GPPassos** [comment]
I'd also like this for the iOS client.

**Comment by fltw** [comment]
iOS client +1. This is very annoying.

**Comment by tonysung** [comment]
iOS client +1. This is very annoying.

**Comment by fltw** [comment]
LOL

**Comment by clivepaterson** [comment]
Oh yeah, really looking forward to this feature too.

**Comment by ailnlv** [comment]
Is this not an option anymore? With the update to version 2.91.90072 I don't get any muted conversations on the badge count anymore. Is there a way to bring them back?

**Comment by Tocher** [comment]
Pls, make this an option, i'd like to see badge count, without any push notifications

**Comment by d-ph** [comment]
Hi,

A slight off-topic. I was facing the same problem, until I realized, that I can achieve almost the same thing by changing the notification options of a channel (or globally) to `Mentions of my name and highlights only`. For me, this is actually better than muting the channel, because this still sends desktop notifications, when someone at-mentions me or uses the at-channel handle. Otherwise, when people just have a casual chat on the channel, desktop notifications are not sent and the channel name gets highlighted (without the count badge, though). I recommend trying this out.

![image](https://cloud.githubusercontent.com/assets/4347095/25146860/6033d940-246d-11e7-96a9-102f6c49bc23.png)

Cheers.

**Comment by ailnlv** [comment]
@d-ph how are you getting those options? I can only turn notifications on and off on groups. Which client are you using?

**Comment by d-ph** [comment]
The screenshot is from the app for Windows, but it shouldn't matter, because the desktop app is the same for all OSes.

Maybe another screenshot would help:

![image](https://cloud.githubusercontent.com/assets/4347095/25150877/63d66cf8-247b-11e7-9047-31c761ec5cb9.png)

![image](https://cloud.githubusercontent.com/assets/4347095/25150974/bb384c64-247b-11e7-955e-724e83f5ee7f.png)

**Comment by ailnlv** [comment]
It does matter. There are two clients for OSX: one is [telegram-desktop](https://github.com/telegramdesktop/tdesktop), which is multi platform. The other one is this one, which is written specifically for OSX and has different features. The interface looks completely different from your screenshot and there's nothing similar to what you're proposing (though I wish we could do that).

**Comment by d-ph** [comment]
Sorry, you're right.

**Comment by vgrebenschikov** [comment]
Please make the feature optional, I do not want to hear notifications from muted chats but I'd like to see there there are messages in them. Like email client shows number of unread mails.

Also, now the behavior is different with iOS client (there it shows number even for muted chats).

**Comment by jennwangster** [comment]
+1
