### ISSUE TITLE
Stickers navigation bar moves to opposite way

### ISSUE THREAD

**Issue by stevenbarragan** [overtake/telegram#166]
In the "navigation bar" (where you can navigate between the kind of stickers that you have), when I scroll to the right it goes to the left, and the same happen in the opposite way.

I'm using trackpad / magic mouse.

<img width="332" alt="screen shot 2015-07-22 at 5 56 27 pm" src="https://cloud.githubusercontent.com/assets/850686/8840797/0a4df1fe-309b-11e5-8547-264b551d03d3.png">

**Comment by erisdev** [comment]
confirming this. it's really obnoxious.

**Comment by LukeLR** [comment]
Maybe Inverted Scrolling is activated? (In System Preferences > Trackpad (or Mouse)) Then Mac OS makes scrolling react the opposite way, as it would on touch screen devices. Think of your Smartphone: to see what's left in a horizontal scrolling list, you need to drag your finger to the right. To see what's at the top of a webpage, you need to drag your finger down.

**Comment by erisdev** [comment]
@lukelr that's kind of the issue. i have natural scrolling _enabled_ but the bar at the top of the stickers window is acting as if it's _disabled_.

**Comment by LukeLR** [comment]
Sorry if I still don't get it, but if you're using natural scrolling, than it behaves exactly as it should, doesn't it? When I scroll to the right, it takes me to the left, because I'm moving the content to the right. Just try it out in Finder, when a window is too narrow to display the complete width of it's content: Scrolling to the right shows you what's on the left, since with natural scrolling the content always follows the direction of the scrolling.

**Comment by erisdev** [comment]
augh, after turning natural scrolling off and back on, it is behaving correctly, as you describe. it wasn't before. what the heck :weary:

i promise i'm not stupid or crazy and it was actually going the wrong way before.

well, at least it works now.
