### ISSUE TITLE
Export conversation

### ISSUE THREAD

**Issue by finchapps** [overtake/telegram#174]
An export conversation function like WhatsApp has.
A text file you can email to yourself. With or without all media

**Comment by LukeLR** [comment]
I'd also love to see this, since I am always trying to grab copies of my chats with scripts for vysheng/tg-cli. Although I don't think that e-mailing the file would be the preferred solution, just saving the text file somewhere, together with a folder for the media, would be sufficient. If you want to e-mail it, you could still do afterwards.

**Comment by LukeLR** [comment]
+1

**Comment by ryush00** [comment]
:+1:

**Comment by nigelreg** [comment]
+1

**Comment by jaimejim** [comment]
I'd welcome this as well. Export as HTML file, with links to audio, pictures and photos.

+++++++++1
