### ISSUE TITLE
App sends "/start" to bots automatically

### ISSUE THREAD

**Issue by francescotonini** [overtake/telegram#206]
Hi, randomly Telegram for OS X sends automatically "/start" messages to bots. How is it possibile? Please see attached video for more details.

http://1drv.ms/1HvE6hm

Thanks!

**Comment by overtake** [comment]
Ok. Fixed this, wait next beta or stable version. Thanks you!

**Comment by matteocontrini** [comment]
This issue has been only partially fixed.
When starting a conversation with a new bot, a wrong command is sent. "/start" is shown in the client, but, for an Italian installation, the bot is actually receiving "/start Avvia".
This issue is causing a lot of problems to users because bots are not ready to handle this.
