### ISSUE TITLE
Support Full Screen Shortcut

### ISSUE THREAD

**Issue by kevur** [overtake/telegram#31]
Would you consider building in support for the default Full Screen Keyboard shortcut (ctrl-cmd-f)?

**Comment by pedrokleiz** [comment]
I'd like this as well.

**Comment by valentinocossar** [comment]
I'd like this too.

**Comment by pedrokleiz** [comment]
I'm currently trying to make telegram on the newest Qt project on OS X, I
could use some help making it on the Official port:
https://github.com/telegramdesktop/tdesktop

I'd like this too.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/overtake/telegram/issues/31#issuecomment-227268477>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AGgyoCFy7fimF3GMdwR8xYvpsV75BcPhks5qNv_VgaJpZM4C6kqv>
.

**Comment by valentinocossar** [comment]
Why? ☹️ I'm really interested in this simple feature.

**Comment by overtake** [comment]
@valentinocossar Try add:)

**Comment by valentinocossar** [comment]
I don't know how 😓

**Comment by valentinocossar** [comment]
I don't know how 😓

**Comment by valentinocossar** [comment]
Please, re-open this issue with the enanchement tag, so people can understand that the feature is missing on this app. This is the only app on my Mac that not support cmd + shift + f to toggle full screen mode. I'll do my best to find someone who can add this feature to this app if you don't have time to do it. 😞
