### ISSUE TITLE
There is no integration in OS X share menu

### ISSUE THREAD

**Issue by rreina** [overtake/telegram#71]
In share context menu you can export the selected content with other apps such Facebook or Twitter but Telegram is not on the list. Can it be integrated into OS X share menu? This make easier to share some things. E.g.: in the new Photos app you cannot access the actual file of every photo but you can select share to send it to another app.

![screen shot 2015-03-04 at 22 17 26](https://cloud.githubusercontent.com/assets/3082477/6493636/51df5e74-c2bc-11e4-88b8-4e38127c50a0.png)

**Comment by asux** [comment]
:+1:

**Comment by nmat** [comment]
+1

**Comment by blaze182** [comment]
+1

**Comment by vladaverin24** [comment]
+1

**Comment by nv2089** [comment]
+1

**Comment by remzr7** [comment]
+1

**Comment by imran0** [comment]
+1

**Comment by ialexryan** [comment]
+1

**Comment by overtake** [comment]
ok, see it in next week 😎

**Comment by iyee** [comment]
@overtake any news?

**Comment by remzr7** [comment]
+1

**Comment by overtake** [comment]
i coded this, but not released. wait news for this. Because i need migrate authkeys to keychain for working this.

**Comment by sergiovilar** [comment]
+1

**Comment by ialexryan** [comment]
@overtake can we reopen this issue then until it's released? thanks for making it! 😁

**Comment by Fahrradflucht** [comment]
and another update without the share extension... when can we expect this to ship?

**Comment by overtake** [comment]
@Fahrradflucht New update only with fixes. Mb next

**Comment by overtake** [comment]
Good news Guys! I added share-extension in 1.80 available now in AppsStore

**Comment by sergiovilar** [comment]
@overtake thank you!

**Comment by LukeLR** [comment]
Thanks! That's great!

**Comment by bharathyes** [comment]
Using Mac OS X El Captain v10.11.3. Can't see Telegram in my **_Share_** menu. Have checked if it has been turned off but it isn't available there too. Don't know why this is the case. The app I am using is **Version 2.16.47508**. Has the feature been removed or something ?

**Comment by bharathyes** [comment]
@digiltd Like I mentioned, Telegram doesn't show up on the Extensions>Share Menu. I have got various options like Add to Reading List, Notes, Reminder, OneNote, etc and even some sites I have never heard of like Youku, Sina Weibo but not Telegram. I don't see why this is missing. I have tried reinstalling the app. Downloaded it directly from the site, from the App Store but doesn't work. Kindly let me know the current status on this feature.

**Comment by digiltd** [comment]
@bharathyes Sorry, I didn't spot you had already mentioned that.

There are a couple of versions of the app which is confusing. It was only today when I wanted to use the share extension that I discovered the other app. I was previously using the Telegram Desktop but from your version number you were using the one with the share menu.

This is just from my experiences today with it. I installed [this version from the Mac App Store](https://itunes.apple.com/gb/app/telegram/id747648890?mt=12)

Which gave me Telegram in my share menu.

I removed the App Store version and then installed the app with the same version number that is available on the Telegram site [https://macos.telegram.org/](https://macos.telegram.org/)

Telegram was no longer in my share menu.

So keeping the non Mac App Store version where it was installed, I also installed the App Store version. Which installed it into a folder in my Applications folder.

The share menu works again

The two versions might become a problem, we shall see. 

I don't think it is a requirement that an app must come from the App Store in order to have a share extension. Mailplane isn't from the App Store and that has an extension.

Usually drag and drop or copy paste is fine, but it is needed for the crappy apps that don't allow that and force you to use these stupid share menus. (the same apps that use the equally crappy way of saving files with all the extra steps and pointless animations)

**Comment by sundaycreative** [comment]
+1

**Comment by radscale** [comment]
+1

**Comment by kruppakinga** [comment]
+1

**Comment by tiktuk** [comment]
Share extension still only available in App Store version of Telegram.

**Comment by overtake** [comment]
@tiktuk correct.

**Comment by FarzanDb** [comment]
correct!

**Comment by sn0wst0rm** [comment]
Could you also add this feature to Telegram Desktop version? it would be great

**Comment by overtake** [comment]
@sn0wst0rm Why u using desktop? Use native client

**Comment by sn0wst0rm** [comment]
@overtake because I think it is much more easy to use, I like the theming capabilities (which I remember native app didn't have) and I also like much more the graphics in general. The only cons are the integration with macOS for sharing and the touchbar, but I still prefer being able to theme the app as I want

**Comment by overtake** [comment]
@sn0wst0rm This is repo only for native app

**Comment by sn0wst0rm** [comment]
@overtake yes I noticed it too late, sorry 😅. However the source code you provided on GitHub for the native app seems broken, many libraries are missing (the trees you used are no longer aviable). I have tried to clone the master branch of each of them, but still I can't get it built (getting a semantic issue at the end of TGTLSerialization.mm)

**Comment by overtake** [comment]
@sn0wst0rm because it legacy repository. Not App written on swift language and source code will available later

**Comment by overtake** [comment]
:bowtie:

**Comment by overtake** [comment]
:bowtie:
